DROP TABLE IF EXISTS T_BANK ;
CREATE TABLE T_BANK (BANK_ID_T_BANK INT AUTO_INCREMENT NOT NULL,
BANK_Name_T_BANK VARCHAR(50),
BANK_AmmountBANK_Ammount_T_BANK BIGINT,
PRIMARY KEY (BANK_ID_T_BANK)) ENGINE=InnoDB;

DROP TABLE IF EXISTS T_CLIENT ;
CREATE TABLE T_CLIENT (CLIENT_ID_T_CLIENT INT AUTO_INCREMENT NOT NULL,
CLIENT_Lastname_T_CLIENT VARCHAR(50),
CLIENT_Firstname_T_CLIENT VARCHAR(50),
CLIENT_City_T_CLIENT VARCHAR(50),
CLIENT_ZipCode_T_CLIENT VARCHAR(4),
PRIMARY KEY (CLIENT_ID_T_CLIENT)) ENGINE=InnoDB;

DROP TABLE IF EXISTS T_ACCOUNT ;
CREATE TABLE T_ACCOUNT (CLIENT_ID_T_CLIENT **NOT FOUND** AUTO_INCREMENT NOT NULL,
BANK_ID_T_BANK **NOT FOUND** NOT NULL,
ACCOUNT_ID_T_ACCOUNT INT,
ACCOUNT_BankNumber_T_ACCOUNT VARCHAR(19),
ACCOUNT_Amount_T_ACCOUNT DECIMAL,
PRIMARY KEY (CLIENT_ID_T_CLIENT,
 BANK_ID_T_BANK)) ENGINE=InnoDB;

DROP TABLE IF EXISTS T_LOAN ;
CREATE TABLE T_LOAN (CLIENT_ID_T_CLIENT **NOT FOUND** AUTO_INCREMENT NOT NULL,
BANK_ID_T_BANK **NOT FOUND** NOT NULL,
LOAN_ID_T_LOAN BIGINT,
LOAN_Account_T_LOAN VARCHAR(19),
LOAN_Amount_T_LOAN DECIMAL,
PRIMARY KEY (CLIENT_ID_T_CLIENT,
 BANK_ID_T_BANK)) ENGINE=InnoDB;

ALTER TABLE T_ACCOUNT ADD CONSTRAINT FK_T_ACCOUNT_CLIENT_ID_T_CLIENT FOREIGN KEY (CLIENT_ID_T_CLIENT) REFERENCES T_CLIENT (CLIENT_ID_T_CLIENT);

ALTER TABLE T_ACCOUNT ADD CONSTRAINT FK_T_ACCOUNT_BANK_ID_T_BANK FOREIGN KEY (BANK_ID_T_BANK) REFERENCES T_BANK (BANK_ID_T_BANK);
ALTER TABLE T_LOAN ADD CONSTRAINT FK_T_LOAN_CLIENT_ID_T_CLIENT FOREIGN KEY (CLIENT_ID_T_CLIENT) REFERENCES T_CLIENT (CLIENT_ID_T_CLIENT);
ALTER TABLE T_LOAN ADD CONSTRAINT FK_T_LOAN_BANK_ID_T_BANK FOREIGN KEY (BANK_ID_T_BANK) REFERENCES T_BANK (BANK_ID_T_BANK);
