# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required
# docker Compose version v2.30.3-desktop.1

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php83
    ports:
      - 8080:80
    volumes:
      - ./php:/var/www/html
  db:
    image: mysql:8.0
    container_name: mysql8
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: demo
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
    volumes:
      - ./dbdata:/var/lib/mysql rw
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: MyAdmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  php:
  dbdata: