SELECT * FROM `T_EMPRUNT_TRI`;
SELECT * FROM `T_CLIENT_TRI`;
SELECT count(*) FROM T_EMPRUNT_TRI A JOIN `T_CLIENT_TRI`
N ON A.id_client = N.id_client HAVING COUNT(*) = 3;
DELIMITER $$
CREATE TRIGGER TRG_INS_EMPRUNT
    BEFORE INSERT 
    ON T_EMPRUNT_TRI
    FOR EACH ROW
    BEGIN
        IF EXISTS(SELECT 1 FROM T_EMPRUNT_TRI A JOIN NEW N ON A.id_client = N.id_client HAVING COUNT(*) = 3) THEN
            ROLLBACK;
        END IF;    
    END $$
DELIMITER ;
INSERT INTO `T_EMPRUNT_TRI` (id_client,type_emprunt)
VALUES(9,'A');